display_name: Coppelia
icon: assets/logo_app_icon.svg
metainfo: linux/packaging/com.matelsky.coppelia.metainfo.xml

build_arch: x86_64

actions:
  - name: Run Coppelia
    label: coppelia
    arguments: []

keywords:
  - Music
  - Jellyfin
  - Streaming

generic_name: Music Streaming Client

categories:
  - AudioVideo
  - Music

startup_notify: true
